--- 
- name: assignment
  hosts: all 
  vars_prompt:
    name: username
    prompt: enter the user name
    private: false
  tasks:
    - name: running the id command
      ansible.builtin.command: id '{{ username }}'
      register: Output
    - name: just checking the condition
      ansible.builtin.debug
        msg: Output.rc 
    # - name: create the user if not present
    #   ansible.builtin.user:
    #     name: '{{ username }}'
    #     state: present
    #   when: Output.rc ! == 0
        
   