--- 
- name: checking the loops
  hosts: all 
  tasks:
    - name: install via loops
      ansible.builtin.package:
        name: "{{ item }}"
        state:  present
      loop:
        - wget
        - curl
        - net-tools
        - nmap