--- 
- name: checking the loops
  hosts: all 
  tasks:
    - name: install via loops
      ansible.builtin.package:
        name:
        state:
      loop:
        - wget
        - curl
        - net-tools
        - nmap