--- 
- name: checking the working way of handlers
  hosts: all 
  become: yes
  tasks: 
    - name: install the wget
      ansible.builtin.package:
        name: wgett
        state: present
      register: output
      ignore_errors: true

      
  
  handlers:
    - name: i am comming from the handlers section
      ansible.builtin.debug:
        msg: now i am running the handler 
      when: output.rc != 0