---
- name: install tree
  hosts: all
  become:  yes
  tasks:
    - name: tree software
      ansible.builtin.apt:
        name: tree
        state: present
        update_cache: yes
    - name: print the all variables
      ansible.builtin.debug:
        var: absible_facts  
        
        
