---
- name: installing the httpd
  become: yes
  hosts: all
  vars: 
    NAME: httpd
  tasks: 
    - name: checking the ansible package
      ansible.builtin.package:
        name: '{{ NAME }}'
        state: present 