--- 
- name: checking the variabless from the play 
  hosts: all 
  vars:
   NAME: SRINU
   COURSE: AWS WITH DEVOPS
   DURATION: 120 hours
  tasks:
    - name: printing the variables
      ansible.builtin.debug: 
        msg: 'Hello {{ NAME }}, welcome to the course {{ COURSE }} and duration is {{ DURATION }}'